server:
  port: 8080
spring:
#  profiles:
#    active: @spring.active@
# autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  datasource:
      name: graduationdesign
      url: jdbc:mysql://localhost:3306/graduationdesign?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&tinyInt1isBit=false
      username: root
      password: 123456
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: com.mikey.design.mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.mikey.design.entity # 注意：对应实体类的路径
  configuration:
#  驼峰法命名
    map-underscore-to-camel-case: false
#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
#  打印日志
logging:
  level:
    #Mapper所在的包
    com.mikey.design.mapper: debug
